Traceback (most recent call last):
  File "/home/rjbc76/mambaforge/envs/webscraping-for-humanities/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/rjbc76/mambaforge/envs/webscraping-for-humanities/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjbc76/mambaforge/envs/webscraping-for-humanities/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjbc76/mambaforge/envs/webscraping-for-humanities/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjbc76/mambaforge/envs/webscraping-for-humanities/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/rjbc76/mambaforge/envs/webscraping-for-humanities/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/rjbc76/mambaforge/envs/webscraping-for-humanities/lib/python3.11/site-packages/nbclient/client.py", line 608, in async_setup_kernel
    yield
  File "/home/rjbc76/mambaforge/envs/webscraping-for-humanities/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/rjbc76/mambaforge/envs/webscraping-for-humanities/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/rjbc76/mambaforge/envs/webscraping-for-humanities/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
h2_next_siblings.text
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[12], line 1[0m
[0;32m----> 1[0m [43mh2_next_siblings[49m[38;5;241;43m.[39;49m[43mtext[49m

File [0;32m~/mambaforge/envs/webscraping-for-humanities/lib/python3.11/site-packages/bs4/element.py:2289[0m, in [0;36mResultSet.__getattr__[0;34m(self, key)[0m
[1;32m   2287[0m [38;5;28;01mdef[39;00m [38;5;21m__getattr__[39m([38;5;28mself[39m, key):
[1;32m   2288[0m [38;5;250m    [39m[38;5;124;03m"""Raise a helpful exception to explain a common code fix."""[39;00m
[0;32m-> 2289[0m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(
[1;32m   2290[0m         [38;5;124m"[39m[38;5;124mResultSet object has no attribute [39m[38;5;124m'[39m[38;5;132;01m%s[39;00m[38;5;124m'[39m[38;5;124m. You[39m[38;5;124m'[39m[38;5;124mre probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?[39m[38;5;124m"[39m [38;5;241m%[39m key
[1;32m   2291[0m     )

[0;31mAttributeError[0m: ResultSet object has no attribute 'text'. You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?
AttributeError: ResultSet object has no attribute 'text'. You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?

